// Code generated by raindrop build, DO NOT EDIT.
import { Ai, Annotation, App, Logger, MRNObject, ServiceStub, SmartMemory, Tracer,  } from '@liquidmetal-ai/raindrop-framework';

export interface Env {
  _raindrop: {
    app: App;
  };
  AI: Ai;
  annotation: Annotation<Omit<MRNObject, 'type' | 'applicationName' | 'versionId'>>;
  CHAT_AGENT: ServiceStub<import('../chat-agent/index.js').default>;
  CHAT_HISTORY: SmartMemory;
  CRIME_AGENT: ServiceStub<import('../crime-agent/index.js').default>;
  CRIME_API_KEY: string;
  EARTHQUAKE_AGENT: ServiceStub<import('../earthquake-agent/index.js').default>;
  EARTHQUAKE_API_KEY: string;
  FLOOD_AGENT: ServiceStub<import('../flood-agent/index.js').default>;
  FLOOD_API_KEY: string;
  HIGHWAY_AGENT: ServiceStub<import('../highway-agent/index.js').default>;
  HIGHWAY_API_KEY: string;
  logger: Logger;
  MAP_AGENT: ServiceStub<import('../map-agent/index.js').default>;
  NOISE_AGENT: ServiceStub<import('../noise-agent/index.js').default>;
  NOISE_API_KEY: string;
  tracer: Tracer;
  ZILLOW_AGENT: ServiceStub<import('../zillow-agent/index.js').default>;
  ZILLOW_API_KEY: string;
}
